name: Test action

on:
  pull_request:
    paths:
      - 'action.yml'
      - '.github/workflows/test.yml'
      - 'tests/**'
  push:
    branches:
      - reishoku
    paths:
      - 'action.yml'
      - '.github/workflows/test.yml'
      - 'tests/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-default:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run rpmlint action (default)
        uses: ./
        with:
          path: tests

  test-strict:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run rpmlint action (strict)
        uses: ./
        with:
          path: tests
          config: tests/.rpmlint.toml
          strict: 'true'

  test-no-spec:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run rpmlint action (no spec files)
        uses: ./
        with:
          path: .github

  test-custom-config:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run rpmlint action (custom config)
        uses: ./
        with:
          path: tests
          config: tests/.rpmlint.toml
